#    多个rabbit定义
spring:
  cloud:
    stream:
      binders:
         rabbit:
            type: rabbit
            envirorunent:
              spring:
                rabbitmq:
                  host: 127.0.0.1
                  prot: 5672
                  username: guest
                  password: guest
#          rabbit2:
#            type: rabbit
#            envirorunent:
#              spring:
#                rabbitmq:
#                  host: 127.0.0.1
#                  prot: 5672
#                  username: guest
#                  password: guest

