#    多个rabbit定义
spring:
# rabbitmq 控制台 localhost:15672
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  cloud:
    stream:
      binders:
         rabbit:
            type: rabbit
            envirorunent:
              spring:
                rabbitmq:
                  host: 127.0.0.1
                  prot: 5673
                  username: guest
                  password: guest
#          rabbit2:
#            type: rabbit
#            envirorunent:
#              spring:
#                rabbitmq:
#                  host: 127.0.0.1
#                  prot: 5672
#                  username: guest
#                  password: guest

